language: node_js
node_js:
- 8
env:
  global:
    - SAUCE_USERNAME=Exonum
  matrix:
    secure: IkP6tEnVX5p5ChNfC/X5RucopgCwQFEc2G3QBGG1gYYvL/xyxvHUy9xUjiycds77gyLHlXfHD8chgiOtwqBe6JrkSkc4oo3UF3AhGpSOMWpRf7SAriR+loK4PrOAfkGWKBITf3U6n+sv+13823udwOKaLuad4pelupWwB4FGbnqAg1B2rpwe0pSgCg182j2hU2/YdeOLEZlAVpSeEAjetlLrEcdfTKHsjzCGvWmwrvUeUS1A6M/Hs1LS1Un3LOWY9/dmpXr7un1oCvR7S5UcGZB8KTK+brYtWofwTH3GV1e8QxrgVHx4fUJLSlEXqqPzSFR0kVjcMPrx7a3uYT1wV59ABoEpz4z019PpWM8BMWRPKx/LrzNFMsF9P185BXMfZ5zmSTy2R6y8vkt7k7+AV8Q4os4POfCFxGGHzwNGhroNitDxITD0sRP3u1MW3EPVuJ3py3SPSuEEk9OOoLb4sBZkzcLDFm8whu+lbNXEfI4xrbmFlI2thxWL3/mFhE32ElX8wpoNfVHccWLaZAMtk1bZEMmWeJ8Ygn70ybgrW12GUtkkFBCubiu5366c4BfU/BvFAwF4Ulk7mITbqFEMA8DgWMBuLlrVsrcUbubRT8Z5ASetQ5A95jyyRJ/3Xj0Mf8A6HJElDYhzI/Ax9oZnOUA0QZAnOiDGItB6W1zQEuM=
cache:
  directories:
  - node_modules
script:
- npm run compile
- npm run test
- npm run test-saucelabs
after_success:
- npm run coveralls
