language: node_js
node_js:
- 8
env:
  global:
    - SAUCE_USERNAME=Exonum
  matrix:
    secure: hi21csEkPt8KcRECyxxXAA4OnhZ31H+KF6N4AmTPVxSEpSOZlVP9bv2HKQsTBuyV3Cxnp0Dzd0a1iKL5HH/kVKbzKKbNC1Ngt2XelBDTaSundE9nc0etpaNBFEWFxxV0xTAq80UwR1CBas0HCUWNjlwByuSaWj/4yvfvAyeWc2X6fHZYe4HRjJIuT0AFTPlv+Dn6SHYY/1OayxWdX2LPHTxstVBQQe74Wx4mu6CmOrY1tVIIPHRl0WwlRtZx0Kq7culDcvY0uaQ/26n4jI5336N9GT9O63GD54XdsncPLhfe424hGlLSBBZX0ohw75BVGkM3a4Fcm+k/LycfhnZGsVFveBs6DX7kM9/cHjgH5qivr2w3Zh40guZSEzRnTHZgcGkNPW/fVmNsK1jcH+VJ0saB5r3LEvHYqvtzmajv3FTAnZcamYRhRc9ywoffNpGwd8nxtWSTgpmCW5w8pAYNI8Ezl/UNO+dHetnCsiOkGEUGvS9+xBjngbfHXq83idhpXdudNe75MexqV+YskLn+WQx+zShwgcavAf96oZoK/+pl6gJLXWzsFUuDM1Uqo0E8ePfM3TgQAvdP3og9uoJMFzLEBv0TZKYQAHF+z1wVi5RwNRqEepVc10m/UsE2TPt4fzQyCoPELaawZyqICuWnKhvT6XJ29W7s/JGTPXXKBH4=
cache:
  directories:
  - node_modules
script:
- npm run compile
- npm run test
- npm run test-saucelabs
after_success:
- npm run coveralls
deploy:
  provider: npm
  email: exonum.bitfury@gmail.com
  api_key:
    secure: fvkH3N3pGbixckdhmT0jB0QCp+MzzwO2DAwEHiALbXKYlhR1Gq13aNvrvf8G1+n5gCy07wlOJqZd7eIMMiNt12bUPrLti23KRW6mbVWag2SXRwALXA7JOZ0f5vqmTgSewc3hnTTXLtXSzHwnCDXex3rcm/Xmm5LOTbZwFAeKuvLfsaLCODQ6eflJawGgwSXxbc8ZZUjEjc/F0IIbZZKtsFFX98vVDtbHjRnUENlH7tQ1SQhCe0Lowg46j2BI3yXpen76OATXNVMaEzoH3VGZbkkVnbw3fHTPatXnfqgRdfH58RAPzdTX1y1otojqzQURs3HOVVvw8y7Edj4p8x8wr3wCWvmkoDD4heaTMf7D4wem5/zrPFQV34QWYXBuoqm+xPhpZLlVwwoiCYopFRoWT4NqWpbYzh1N/f6vkPDv9Mjr9sL0XM+egsx4b2xpIK6qjl3aWelmDLow6rXZabIYQtcYjCEuMrFu/IglZI1fsuAyHiOB9W2WI3JRv0a8U8h7sOGGDmb6eUL4H0JgM8+q2pgDooTllkyt8aN3I0eKo2C9YP2TcxURhtPUarkad4PAsHyDn9oS3onqW/ZtBfZb/QwMtOn4G/xaO3ss5enjSG+oN1UUwO4JoCFm/mUKgumNlxYgtz9R/DF1C5K5rP5rXdwsQF/Vt3r1K3PRLhxdv3k=
  on:
    branch: master
    tags: true
    repo: exonum/exonum-client-anchoring
